[package]
name = "daemon"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "textexpander"
path = "src/main.rs"

[dependencies]
rule_codec = { path = "../../crates/rule_codec" }
engine = { path = "../../crates/engine" }
injector = { path = "../../crates/injector" }
config_manager = { path = "../../crates/config_manager" }
workspace_config = { path = "../../crates/workspace_config" }
rdev = {  version = "0.5", features = ["unstable_grab"] }
tray-icon = "0.24"
menu = "0.6"
image = "0.25"
winit = "0.30"

[build-dependencies]
embed-resource = "3.0.11"
