[package]
name = "gui"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = "1.3"
workspace_config = { path = "../../crates/workspace_config" }
rule_codec = { path = "../../crates/rule_codec" }

[build-dependencies]
slint-build = "1.3"
embed-resource = "3.0"

[[bin]]
name = "RTERM"
path = "src/main.rs"
